apiVersion: v1
kind: Secret
metadata:
  name: msk-credentials
  namespace: kafka
type: Opaque
stringData:
  sasl.jaas.config: >-
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username="msk-user" password="msk-password";

---
apiVersion: v1
kind: Secret
metadata:
  name: confluent-cloud-credentials
  namespace: kafka
type: Opaque
stringData:
  sasl.jaas.config: >-
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="<CCLOUD_API_KEY>" password="<CCLOUD_API_SECRET>";
